/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultantIndexRouteImport } from './routes/consultant/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCreateUserRouteImport } from './routes/admin/create-user'
import { Route as ConsultantSeedCreateRouteImport } from './routes/consultant/seed/create'
import { Route as ConsultantRecommendationCreateRouteImport } from './routes/consultant/recommendation/create'
import { Route as ClientLandCreateRouteImport } from './routes/client/land/create'
import { Route as AdminUpdateUserIdRouteImport } from './routes/admin/update-user.$id'
import { Route as ConsultantSeedSeedIdIndexRouteImport } from './routes/consultant/seed/$seedId/index'
import { Route as ConsultantRecommendationRecIdIndexRouteImport } from './routes/consultant/recommendation/$recId/index'
import { Route as ClientLandLandIdIndexRouteImport } from './routes/client/land/$landId/index'
import { Route as ConsultantSeedSeedIdUpdateRouteImport } from './routes/consultant/seed/$seedId/update'
import { Route as ConsultantRecommendationRecIdUpdateRouteImport } from './routes/consultant/recommendation/$recId/update'
import { Route as ClientLandLandIdUpdateRouteImport } from './routes/client/land/$landId/update'
import { Route as ClientLandLandIdValveCreateRouteImport } from './routes/client/land/$landId/valve/create'
import { Route as ClientLandLandIdSensorCreateRouteImport } from './routes/client/land/$landId/sensor/create'
import { Route as ClientLandLandIdPumpCreateRouteImport } from './routes/client/land/$landId/pump/create'
import { Route as ClientLandLandIdPlantCreateRouteImport } from './routes/client/land/$landId/plant/create'
import { Route as ClientLandLandIdPestControlCreateRouteImport } from './routes/client/land/$landId/pest-control/create'
import { Route as ClientLandLandIdAutomationCreateRouteImport } from './routes/client/land/$landId/automation/create'
import { Route as ClientLandLandIdValveValveIdIndexRouteImport } from './routes/client/land/$landId/valve/$valveId/index'
import { Route as ClientLandLandIdSensorSensorIdIndexRouteImport } from './routes/client/land/$landId/sensor/$sensorId/index'
import { Route as ClientLandLandIdPumpPumpIdIndexRouteImport } from './routes/client/land/$landId/pump/$pumpId/index'
import { Route as ClientLandLandIdPlantPlantIdIndexRouteImport } from './routes/client/land/$landId/plant/$plantId/index'
import { Route as ClientLandLandIdPestControlPestIdIndexRouteImport } from './routes/client/land/$landId/pest-control/$pestId/index'
import { Route as ClientLandLandIdAutomationAutomationIdIndexRouteImport } from './routes/client/land/$landId/automation/$automationId/index'
import { Route as ClientLandLandIdValveValveIdUpdateRouteImport } from './routes/client/land/$landId/valve/$valveId/update'
import { Route as ClientLandLandIdSensorSensorIdUpdateRouteImport } from './routes/client/land/$landId/sensor/$sensorId/update'
import { Route as ClientLandLandIdPumpPumpIdUpdateRouteImport } from './routes/client/land/$landId/pump/$pumpId/update'
import { Route as ClientLandLandIdPlantPlantIdUpdateRouteImport } from './routes/client/land/$landId/plant/$plantId/update'
import { Route as ClientLandLandIdPestControlPestIdUpdateRouteImport } from './routes/client/land/$landId/pest-control/$pestId/update'
import { Route as ClientLandLandIdAutomationAutomationIdUpdateRouteImport } from './routes/client/land/$landId/automation/$automationId/update'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantIndexRoute = ConsultantIndexRouteImport.update({
  id: '/consultant/',
  path: '/consultant/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateUserRoute = AdminCreateUserRouteImport.update({
  id: '/admin/create-user',
  path: '/admin/create-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantSeedCreateRoute = ConsultantSeedCreateRouteImport.update({
  id: '/consultant/seed/create',
  path: '/consultant/seed/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantRecommendationCreateRoute =
  ConsultantRecommendationCreateRouteImport.update({
    id: '/consultant/recommendation/create',
    path: '/consultant/recommendation/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandCreateRoute = ClientLandCreateRouteImport.update({
  id: '/client/land/create',
  path: '/client/land/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdateUserIdRoute = AdminUpdateUserIdRouteImport.update({
  id: '/admin/update-user/$id',
  path: '/admin/update-user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantSeedSeedIdIndexRoute =
  ConsultantSeedSeedIdIndexRouteImport.update({
    id: '/consultant/seed/$seedId/',
    path: '/consultant/seed/$seedId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsultantRecommendationRecIdIndexRoute =
  ConsultantRecommendationRecIdIndexRouteImport.update({
    id: '/consultant/recommendation/$recId/',
    path: '/consultant/recommendation/$recId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdIndexRoute = ClientLandLandIdIndexRouteImport.update({
  id: '/client/land/$landId/',
  path: '/client/land/$landId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantSeedSeedIdUpdateRoute =
  ConsultantSeedSeedIdUpdateRouteImport.update({
    id: '/consultant/seed/$seedId/update',
    path: '/consultant/seed/$seedId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsultantRecommendationRecIdUpdateRoute =
  ConsultantRecommendationRecIdUpdateRouteImport.update({
    id: '/consultant/recommendation/$recId/update',
    path: '/consultant/recommendation/$recId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdUpdateRoute = ClientLandLandIdUpdateRouteImport.update({
  id: '/client/land/$landId/update',
  path: '/client/land/$landId/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLandLandIdValveCreateRoute =
  ClientLandLandIdValveCreateRouteImport.update({
    id: '/client/land/$landId/valve/create',
    path: '/client/land/$landId/valve/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdSensorCreateRoute =
  ClientLandLandIdSensorCreateRouteImport.update({
    id: '/client/land/$landId/sensor/create',
    path: '/client/land/$landId/sensor/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdPumpCreateRoute =
  ClientLandLandIdPumpCreateRouteImport.update({
    id: '/client/land/$landId/pump/create',
    path: '/client/land/$landId/pump/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdPlantCreateRoute =
  ClientLandLandIdPlantCreateRouteImport.update({
    id: '/client/land/$landId/plant/create',
    path: '/client/land/$landId/plant/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdPestControlCreateRoute =
  ClientLandLandIdPestControlCreateRouteImport.update({
    id: '/client/land/$landId/pest-control/create',
    path: '/client/land/$landId/pest-control/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdAutomationCreateRoute =
  ClientLandLandIdAutomationCreateRouteImport.update({
    id: '/client/land/$landId/automation/create',
    path: '/client/land/$landId/automation/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdValveValveIdIndexRoute =
  ClientLandLandIdValveValveIdIndexRouteImport.update({
    id: '/client/land/$landId/valve/$valveId/',
    path: '/client/land/$landId/valve/$valveId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdSensorSensorIdIndexRoute =
  ClientLandLandIdSensorSensorIdIndexRouteImport.update({
    id: '/client/land/$landId/sensor/$sensorId/',
    path: '/client/land/$landId/sensor/$sensorId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdPumpPumpIdIndexRoute =
  ClientLandLandIdPumpPumpIdIndexRouteImport.update({
    id: '/client/land/$landId/pump/$pumpId/',
    path: '/client/land/$landId/pump/$pumpId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdPlantPlantIdIndexRoute =
  ClientLandLandIdPlantPlantIdIndexRouteImport.update({
    id: '/client/land/$landId/plant/$plantId/',
    path: '/client/land/$landId/plant/$plantId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdPestControlPestIdIndexRoute =
  ClientLandLandIdPestControlPestIdIndexRouteImport.update({
    id: '/client/land/$landId/pest-control/$pestId/',
    path: '/client/land/$landId/pest-control/$pestId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdAutomationAutomationIdIndexRoute =
  ClientLandLandIdAutomationAutomationIdIndexRouteImport.update({
    id: '/client/land/$landId/automation/$automationId/',
    path: '/client/land/$landId/automation/$automationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdValveValveIdUpdateRoute =
  ClientLandLandIdValveValveIdUpdateRouteImport.update({
    id: '/client/land/$landId/valve/$valveId/update',
    path: '/client/land/$landId/valve/$valveId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdSensorSensorIdUpdateRoute =
  ClientLandLandIdSensorSensorIdUpdateRouteImport.update({
    id: '/client/land/$landId/sensor/$sensorId/update',
    path: '/client/land/$landId/sensor/$sensorId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdPumpPumpIdUpdateRoute =
  ClientLandLandIdPumpPumpIdUpdateRouteImport.update({
    id: '/client/land/$landId/pump/$pumpId/update',
    path: '/client/land/$landId/pump/$pumpId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdPlantPlantIdUpdateRoute =
  ClientLandLandIdPlantPlantIdUpdateRouteImport.update({
    id: '/client/land/$landId/plant/$plantId/update',
    path: '/client/land/$landId/plant/$plantId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdPestControlPestIdUpdateRoute =
  ClientLandLandIdPestControlPestIdUpdateRouteImport.update({
    id: '/client/land/$landId/pest-control/$pestId/update',
    path: '/client/land/$landId/pest-control/$pestId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandLandIdAutomationAutomationIdUpdateRoute =
  ClientLandLandIdAutomationAutomationIdUpdateRouteImport.update({
    id: '/client/land/$landId/automation/$automationId/update',
    path: '/client/land/$landId/automation/$automationId/update',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/consultant': typeof ConsultantIndexRoute
  '/admin/update-user/$id': typeof AdminUpdateUserIdRoute
  '/client/land/create': typeof ClientLandCreateRoute
  '/consultant/recommendation/create': typeof ConsultantRecommendationCreateRoute
  '/consultant/seed/create': typeof ConsultantSeedCreateRoute
  '/client/land/$landId/update': typeof ClientLandLandIdUpdateRoute
  '/consultant/recommendation/$recId/update': typeof ConsultantRecommendationRecIdUpdateRoute
  '/consultant/seed/$seedId/update': typeof ConsultantSeedSeedIdUpdateRoute
  '/client/land/$landId': typeof ClientLandLandIdIndexRoute
  '/consultant/recommendation/$recId': typeof ConsultantRecommendationRecIdIndexRoute
  '/consultant/seed/$seedId': typeof ConsultantSeedSeedIdIndexRoute
  '/client/land/$landId/automation/create': typeof ClientLandLandIdAutomationCreateRoute
  '/client/land/$landId/pest-control/create': typeof ClientLandLandIdPestControlCreateRoute
  '/client/land/$landId/plant/create': typeof ClientLandLandIdPlantCreateRoute
  '/client/land/$landId/pump/create': typeof ClientLandLandIdPumpCreateRoute
  '/client/land/$landId/sensor/create': typeof ClientLandLandIdSensorCreateRoute
  '/client/land/$landId/valve/create': typeof ClientLandLandIdValveCreateRoute
  '/client/land/$landId/automation/$automationId/update': typeof ClientLandLandIdAutomationAutomationIdUpdateRoute
  '/client/land/$landId/pest-control/$pestId/update': typeof ClientLandLandIdPestControlPestIdUpdateRoute
  '/client/land/$landId/plant/$plantId/update': typeof ClientLandLandIdPlantPlantIdUpdateRoute
  '/client/land/$landId/pump/$pumpId/update': typeof ClientLandLandIdPumpPumpIdUpdateRoute
  '/client/land/$landId/sensor/$sensorId/update': typeof ClientLandLandIdSensorSensorIdUpdateRoute
  '/client/land/$landId/valve/$valveId/update': typeof ClientLandLandIdValveValveIdUpdateRoute
  '/client/land/$landId/automation/$automationId': typeof ClientLandLandIdAutomationAutomationIdIndexRoute
  '/client/land/$landId/pest-control/$pestId': typeof ClientLandLandIdPestControlPestIdIndexRoute
  '/client/land/$landId/plant/$plantId': typeof ClientLandLandIdPlantPlantIdIndexRoute
  '/client/land/$landId/pump/$pumpId': typeof ClientLandLandIdPumpPumpIdIndexRoute
  '/client/land/$landId/sensor/$sensorId': typeof ClientLandLandIdSensorSensorIdIndexRoute
  '/client/land/$landId/valve/$valveId': typeof ClientLandLandIdValveValveIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/consultant': typeof ConsultantIndexRoute
  '/admin/update-user/$id': typeof AdminUpdateUserIdRoute
  '/client/land/create': typeof ClientLandCreateRoute
  '/consultant/recommendation/create': typeof ConsultantRecommendationCreateRoute
  '/consultant/seed/create': typeof ConsultantSeedCreateRoute
  '/client/land/$landId/update': typeof ClientLandLandIdUpdateRoute
  '/consultant/recommendation/$recId/update': typeof ConsultantRecommendationRecIdUpdateRoute
  '/consultant/seed/$seedId/update': typeof ConsultantSeedSeedIdUpdateRoute
  '/client/land/$landId': typeof ClientLandLandIdIndexRoute
  '/consultant/recommendation/$recId': typeof ConsultantRecommendationRecIdIndexRoute
  '/consultant/seed/$seedId': typeof ConsultantSeedSeedIdIndexRoute
  '/client/land/$landId/automation/create': typeof ClientLandLandIdAutomationCreateRoute
  '/client/land/$landId/pest-control/create': typeof ClientLandLandIdPestControlCreateRoute
  '/client/land/$landId/plant/create': typeof ClientLandLandIdPlantCreateRoute
  '/client/land/$landId/pump/create': typeof ClientLandLandIdPumpCreateRoute
  '/client/land/$landId/sensor/create': typeof ClientLandLandIdSensorCreateRoute
  '/client/land/$landId/valve/create': typeof ClientLandLandIdValveCreateRoute
  '/client/land/$landId/automation/$automationId/update': typeof ClientLandLandIdAutomationAutomationIdUpdateRoute
  '/client/land/$landId/pest-control/$pestId/update': typeof ClientLandLandIdPestControlPestIdUpdateRoute
  '/client/land/$landId/plant/$plantId/update': typeof ClientLandLandIdPlantPlantIdUpdateRoute
  '/client/land/$landId/pump/$pumpId/update': typeof ClientLandLandIdPumpPumpIdUpdateRoute
  '/client/land/$landId/sensor/$sensorId/update': typeof ClientLandLandIdSensorSensorIdUpdateRoute
  '/client/land/$landId/valve/$valveId/update': typeof ClientLandLandIdValveValveIdUpdateRoute
  '/client/land/$landId/automation/$automationId': typeof ClientLandLandIdAutomationAutomationIdIndexRoute
  '/client/land/$landId/pest-control/$pestId': typeof ClientLandLandIdPestControlPestIdIndexRoute
  '/client/land/$landId/plant/$plantId': typeof ClientLandLandIdPlantPlantIdIndexRoute
  '/client/land/$landId/pump/$pumpId': typeof ClientLandLandIdPumpPumpIdIndexRoute
  '/client/land/$landId/sensor/$sensorId': typeof ClientLandLandIdSensorSensorIdIndexRoute
  '/client/land/$landId/valve/$valveId': typeof ClientLandLandIdValveValveIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/consultant/': typeof ConsultantIndexRoute
  '/admin/update-user/$id': typeof AdminUpdateUserIdRoute
  '/client/land/create': typeof ClientLandCreateRoute
  '/consultant/recommendation/create': typeof ConsultantRecommendationCreateRoute
  '/consultant/seed/create': typeof ConsultantSeedCreateRoute
  '/client/land/$landId/update': typeof ClientLandLandIdUpdateRoute
  '/consultant/recommendation/$recId/update': typeof ConsultantRecommendationRecIdUpdateRoute
  '/consultant/seed/$seedId/update': typeof ConsultantSeedSeedIdUpdateRoute
  '/client/land/$landId/': typeof ClientLandLandIdIndexRoute
  '/consultant/recommendation/$recId/': typeof ConsultantRecommendationRecIdIndexRoute
  '/consultant/seed/$seedId/': typeof ConsultantSeedSeedIdIndexRoute
  '/client/land/$landId/automation/create': typeof ClientLandLandIdAutomationCreateRoute
  '/client/land/$landId/pest-control/create': typeof ClientLandLandIdPestControlCreateRoute
  '/client/land/$landId/plant/create': typeof ClientLandLandIdPlantCreateRoute
  '/client/land/$landId/pump/create': typeof ClientLandLandIdPumpCreateRoute
  '/client/land/$landId/sensor/create': typeof ClientLandLandIdSensorCreateRoute
  '/client/land/$landId/valve/create': typeof ClientLandLandIdValveCreateRoute
  '/client/land/$landId/automation/$automationId/update': typeof ClientLandLandIdAutomationAutomationIdUpdateRoute
  '/client/land/$landId/pest-control/$pestId/update': typeof ClientLandLandIdPestControlPestIdUpdateRoute
  '/client/land/$landId/plant/$plantId/update': typeof ClientLandLandIdPlantPlantIdUpdateRoute
  '/client/land/$landId/pump/$pumpId/update': typeof ClientLandLandIdPumpPumpIdUpdateRoute
  '/client/land/$landId/sensor/$sensorId/update': typeof ClientLandLandIdSensorSensorIdUpdateRoute
  '/client/land/$landId/valve/$valveId/update': typeof ClientLandLandIdValveValveIdUpdateRoute
  '/client/land/$landId/automation/$automationId/': typeof ClientLandLandIdAutomationAutomationIdIndexRoute
  '/client/land/$landId/pest-control/$pestId/': typeof ClientLandLandIdPestControlPestIdIndexRoute
  '/client/land/$landId/plant/$plantId/': typeof ClientLandLandIdPlantPlantIdIndexRoute
  '/client/land/$landId/pump/$pumpId/': typeof ClientLandLandIdPumpPumpIdIndexRoute
  '/client/land/$landId/sensor/$sensorId/': typeof ClientLandLandIdSensorSensorIdIndexRoute
  '/client/land/$landId/valve/$valveId/': typeof ClientLandLandIdValveValveIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/create-user'
    | '/admin'
    | '/client'
    | '/consultant'
    | '/admin/update-user/$id'
    | '/client/land/create'
    | '/consultant/recommendation/create'
    | '/consultant/seed/create'
    | '/client/land/$landId/update'
    | '/consultant/recommendation/$recId/update'
    | '/consultant/seed/$seedId/update'
    | '/client/land/$landId'
    | '/consultant/recommendation/$recId'
    | '/consultant/seed/$seedId'
    | '/client/land/$landId/automation/create'
    | '/client/land/$landId/pest-control/create'
    | '/client/land/$landId/plant/create'
    | '/client/land/$landId/pump/create'
    | '/client/land/$landId/sensor/create'
    | '/client/land/$landId/valve/create'
    | '/client/land/$landId/automation/$automationId/update'
    | '/client/land/$landId/pest-control/$pestId/update'
    | '/client/land/$landId/plant/$plantId/update'
    | '/client/land/$landId/pump/$pumpId/update'
    | '/client/land/$landId/sensor/$sensorId/update'
    | '/client/land/$landId/valve/$valveId/update'
    | '/client/land/$landId/automation/$automationId'
    | '/client/land/$landId/pest-control/$pestId'
    | '/client/land/$landId/plant/$plantId'
    | '/client/land/$landId/pump/$pumpId'
    | '/client/land/$landId/sensor/$sensorId'
    | '/client/land/$landId/valve/$valveId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/create-user'
    | '/admin'
    | '/client'
    | '/consultant'
    | '/admin/update-user/$id'
    | '/client/land/create'
    | '/consultant/recommendation/create'
    | '/consultant/seed/create'
    | '/client/land/$landId/update'
    | '/consultant/recommendation/$recId/update'
    | '/consultant/seed/$seedId/update'
    | '/client/land/$landId'
    | '/consultant/recommendation/$recId'
    | '/consultant/seed/$seedId'
    | '/client/land/$landId/automation/create'
    | '/client/land/$landId/pest-control/create'
    | '/client/land/$landId/plant/create'
    | '/client/land/$landId/pump/create'
    | '/client/land/$landId/sensor/create'
    | '/client/land/$landId/valve/create'
    | '/client/land/$landId/automation/$automationId/update'
    | '/client/land/$landId/pest-control/$pestId/update'
    | '/client/land/$landId/plant/$plantId/update'
    | '/client/land/$landId/pump/$pumpId/update'
    | '/client/land/$landId/sensor/$sensorId/update'
    | '/client/land/$landId/valve/$valveId/update'
    | '/client/land/$landId/automation/$automationId'
    | '/client/land/$landId/pest-control/$pestId'
    | '/client/land/$landId/plant/$plantId'
    | '/client/land/$landId/pump/$pumpId'
    | '/client/land/$landId/sensor/$sensorId'
    | '/client/land/$landId/valve/$valveId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/create-user'
    | '/admin/'
    | '/client/'
    | '/consultant/'
    | '/admin/update-user/$id'
    | '/client/land/create'
    | '/consultant/recommendation/create'
    | '/consultant/seed/create'
    | '/client/land/$landId/update'
    | '/consultant/recommendation/$recId/update'
    | '/consultant/seed/$seedId/update'
    | '/client/land/$landId/'
    | '/consultant/recommendation/$recId/'
    | '/consultant/seed/$seedId/'
    | '/client/land/$landId/automation/create'
    | '/client/land/$landId/pest-control/create'
    | '/client/land/$landId/plant/create'
    | '/client/land/$landId/pump/create'
    | '/client/land/$landId/sensor/create'
    | '/client/land/$landId/valve/create'
    | '/client/land/$landId/automation/$automationId/update'
    | '/client/land/$landId/pest-control/$pestId/update'
    | '/client/land/$landId/plant/$plantId/update'
    | '/client/land/$landId/pump/$pumpId/update'
    | '/client/land/$landId/sensor/$sensorId/update'
    | '/client/land/$landId/valve/$valveId/update'
    | '/client/land/$landId/automation/$automationId/'
    | '/client/land/$landId/pest-control/$pestId/'
    | '/client/land/$landId/plant/$plantId/'
    | '/client/land/$landId/pump/$pumpId/'
    | '/client/land/$landId/sensor/$sensorId/'
    | '/client/land/$landId/valve/$valveId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminCreateUserRoute: typeof AdminCreateUserRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ConsultantIndexRoute: typeof ConsultantIndexRoute
  AdminUpdateUserIdRoute: typeof AdminUpdateUserIdRoute
  ClientLandCreateRoute: typeof ClientLandCreateRoute
  ConsultantRecommendationCreateRoute: typeof ConsultantRecommendationCreateRoute
  ConsultantSeedCreateRoute: typeof ConsultantSeedCreateRoute
  ClientLandLandIdUpdateRoute: typeof ClientLandLandIdUpdateRoute
  ConsultantRecommendationRecIdUpdateRoute: typeof ConsultantRecommendationRecIdUpdateRoute
  ConsultantSeedSeedIdUpdateRoute: typeof ConsultantSeedSeedIdUpdateRoute
  ClientLandLandIdIndexRoute: typeof ClientLandLandIdIndexRoute
  ConsultantRecommendationRecIdIndexRoute: typeof ConsultantRecommendationRecIdIndexRoute
  ConsultantSeedSeedIdIndexRoute: typeof ConsultantSeedSeedIdIndexRoute
  ClientLandLandIdAutomationCreateRoute: typeof ClientLandLandIdAutomationCreateRoute
  ClientLandLandIdPestControlCreateRoute: typeof ClientLandLandIdPestControlCreateRoute
  ClientLandLandIdPlantCreateRoute: typeof ClientLandLandIdPlantCreateRoute
  ClientLandLandIdPumpCreateRoute: typeof ClientLandLandIdPumpCreateRoute
  ClientLandLandIdSensorCreateRoute: typeof ClientLandLandIdSensorCreateRoute
  ClientLandLandIdValveCreateRoute: typeof ClientLandLandIdValveCreateRoute
  ClientLandLandIdAutomationAutomationIdUpdateRoute: typeof ClientLandLandIdAutomationAutomationIdUpdateRoute
  ClientLandLandIdPestControlPestIdUpdateRoute: typeof ClientLandLandIdPestControlPestIdUpdateRoute
  ClientLandLandIdPlantPlantIdUpdateRoute: typeof ClientLandLandIdPlantPlantIdUpdateRoute
  ClientLandLandIdPumpPumpIdUpdateRoute: typeof ClientLandLandIdPumpPumpIdUpdateRoute
  ClientLandLandIdSensorSensorIdUpdateRoute: typeof ClientLandLandIdSensorSensorIdUpdateRoute
  ClientLandLandIdValveValveIdUpdateRoute: typeof ClientLandLandIdValveValveIdUpdateRoute
  ClientLandLandIdAutomationAutomationIdIndexRoute: typeof ClientLandLandIdAutomationAutomationIdIndexRoute
  ClientLandLandIdPestControlPestIdIndexRoute: typeof ClientLandLandIdPestControlPestIdIndexRoute
  ClientLandLandIdPlantPlantIdIndexRoute: typeof ClientLandLandIdPlantPlantIdIndexRoute
  ClientLandLandIdPumpPumpIdIndexRoute: typeof ClientLandLandIdPumpPumpIdIndexRoute
  ClientLandLandIdSensorSensorIdIndexRoute: typeof ClientLandLandIdSensorSensorIdIndexRoute
  ClientLandLandIdValveValveIdIndexRoute: typeof ClientLandLandIdValveValveIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/': {
      id: '/consultant/'
      path: '/consultant'
      fullPath: '/consultant'
      preLoaderRoute: typeof ConsultantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-user': {
      id: '/admin/create-user'
      path: '/admin/create-user'
      fullPath: '/admin/create-user'
      preLoaderRoute: typeof AdminCreateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/seed/create': {
      id: '/consultant/seed/create'
      path: '/consultant/seed/create'
      fullPath: '/consultant/seed/create'
      preLoaderRoute: typeof ConsultantSeedCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/recommendation/create': {
      id: '/consultant/recommendation/create'
      path: '/consultant/recommendation/create'
      fullPath: '/consultant/recommendation/create'
      preLoaderRoute: typeof ConsultantRecommendationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/create': {
      id: '/client/land/create'
      path: '/client/land/create'
      fullPath: '/client/land/create'
      preLoaderRoute: typeof ClientLandCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/update-user/$id': {
      id: '/admin/update-user/$id'
      path: '/admin/update-user/$id'
      fullPath: '/admin/update-user/$id'
      preLoaderRoute: typeof AdminUpdateUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/seed/$seedId/': {
      id: '/consultant/seed/$seedId/'
      path: '/consultant/seed/$seedId'
      fullPath: '/consultant/seed/$seedId'
      preLoaderRoute: typeof ConsultantSeedSeedIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/recommendation/$recId/': {
      id: '/consultant/recommendation/$recId/'
      path: '/consultant/recommendation/$recId'
      fullPath: '/consultant/recommendation/$recId'
      preLoaderRoute: typeof ConsultantRecommendationRecIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/': {
      id: '/client/land/$landId/'
      path: '/client/land/$landId'
      fullPath: '/client/land/$landId'
      preLoaderRoute: typeof ClientLandLandIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/seed/$seedId/update': {
      id: '/consultant/seed/$seedId/update'
      path: '/consultant/seed/$seedId/update'
      fullPath: '/consultant/seed/$seedId/update'
      preLoaderRoute: typeof ConsultantSeedSeedIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/recommendation/$recId/update': {
      id: '/consultant/recommendation/$recId/update'
      path: '/consultant/recommendation/$recId/update'
      fullPath: '/consultant/recommendation/$recId/update'
      preLoaderRoute: typeof ConsultantRecommendationRecIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/update': {
      id: '/client/land/$landId/update'
      path: '/client/land/$landId/update'
      fullPath: '/client/land/$landId/update'
      preLoaderRoute: typeof ClientLandLandIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/valve/create': {
      id: '/client/land/$landId/valve/create'
      path: '/client/land/$landId/valve/create'
      fullPath: '/client/land/$landId/valve/create'
      preLoaderRoute: typeof ClientLandLandIdValveCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/sensor/create': {
      id: '/client/land/$landId/sensor/create'
      path: '/client/land/$landId/sensor/create'
      fullPath: '/client/land/$landId/sensor/create'
      preLoaderRoute: typeof ClientLandLandIdSensorCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/pump/create': {
      id: '/client/land/$landId/pump/create'
      path: '/client/land/$landId/pump/create'
      fullPath: '/client/land/$landId/pump/create'
      preLoaderRoute: typeof ClientLandLandIdPumpCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/plant/create': {
      id: '/client/land/$landId/plant/create'
      path: '/client/land/$landId/plant/create'
      fullPath: '/client/land/$landId/plant/create'
      preLoaderRoute: typeof ClientLandLandIdPlantCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/pest-control/create': {
      id: '/client/land/$landId/pest-control/create'
      path: '/client/land/$landId/pest-control/create'
      fullPath: '/client/land/$landId/pest-control/create'
      preLoaderRoute: typeof ClientLandLandIdPestControlCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/automation/create': {
      id: '/client/land/$landId/automation/create'
      path: '/client/land/$landId/automation/create'
      fullPath: '/client/land/$landId/automation/create'
      preLoaderRoute: typeof ClientLandLandIdAutomationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/valve/$valveId/': {
      id: '/client/land/$landId/valve/$valveId/'
      path: '/client/land/$landId/valve/$valveId'
      fullPath: '/client/land/$landId/valve/$valveId'
      preLoaderRoute: typeof ClientLandLandIdValveValveIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/sensor/$sensorId/': {
      id: '/client/land/$landId/sensor/$sensorId/'
      path: '/client/land/$landId/sensor/$sensorId'
      fullPath: '/client/land/$landId/sensor/$sensorId'
      preLoaderRoute: typeof ClientLandLandIdSensorSensorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/pump/$pumpId/': {
      id: '/client/land/$landId/pump/$pumpId/'
      path: '/client/land/$landId/pump/$pumpId'
      fullPath: '/client/land/$landId/pump/$pumpId'
      preLoaderRoute: typeof ClientLandLandIdPumpPumpIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/plant/$plantId/': {
      id: '/client/land/$landId/plant/$plantId/'
      path: '/client/land/$landId/plant/$plantId'
      fullPath: '/client/land/$landId/plant/$plantId'
      preLoaderRoute: typeof ClientLandLandIdPlantPlantIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/pest-control/$pestId/': {
      id: '/client/land/$landId/pest-control/$pestId/'
      path: '/client/land/$landId/pest-control/$pestId'
      fullPath: '/client/land/$landId/pest-control/$pestId'
      preLoaderRoute: typeof ClientLandLandIdPestControlPestIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/automation/$automationId/': {
      id: '/client/land/$landId/automation/$automationId/'
      path: '/client/land/$landId/automation/$automationId'
      fullPath: '/client/land/$landId/automation/$automationId'
      preLoaderRoute: typeof ClientLandLandIdAutomationAutomationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/valve/$valveId/update': {
      id: '/client/land/$landId/valve/$valveId/update'
      path: '/client/land/$landId/valve/$valveId/update'
      fullPath: '/client/land/$landId/valve/$valveId/update'
      preLoaderRoute: typeof ClientLandLandIdValveValveIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/sensor/$sensorId/update': {
      id: '/client/land/$landId/sensor/$sensorId/update'
      path: '/client/land/$landId/sensor/$sensorId/update'
      fullPath: '/client/land/$landId/sensor/$sensorId/update'
      preLoaderRoute: typeof ClientLandLandIdSensorSensorIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/pump/$pumpId/update': {
      id: '/client/land/$landId/pump/$pumpId/update'
      path: '/client/land/$landId/pump/$pumpId/update'
      fullPath: '/client/land/$landId/pump/$pumpId/update'
      preLoaderRoute: typeof ClientLandLandIdPumpPumpIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/plant/$plantId/update': {
      id: '/client/land/$landId/plant/$plantId/update'
      path: '/client/land/$landId/plant/$plantId/update'
      fullPath: '/client/land/$landId/plant/$plantId/update'
      preLoaderRoute: typeof ClientLandLandIdPlantPlantIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/pest-control/$pestId/update': {
      id: '/client/land/$landId/pest-control/$pestId/update'
      path: '/client/land/$landId/pest-control/$pestId/update'
      fullPath: '/client/land/$landId/pest-control/$pestId/update'
      preLoaderRoute: typeof ClientLandLandIdPestControlPestIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$landId/automation/$automationId/update': {
      id: '/client/land/$landId/automation/$automationId/update'
      path: '/client/land/$landId/automation/$automationId/update'
      fullPath: '/client/land/$landId/automation/$automationId/update'
      preLoaderRoute: typeof ClientLandLandIdAutomationAutomationIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminCreateUserRoute: AdminCreateUserRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClientIndexRoute: ClientIndexRoute,
  ConsultantIndexRoute: ConsultantIndexRoute,
  AdminUpdateUserIdRoute: AdminUpdateUserIdRoute,
  ClientLandCreateRoute: ClientLandCreateRoute,
  ConsultantRecommendationCreateRoute: ConsultantRecommendationCreateRoute,
  ConsultantSeedCreateRoute: ConsultantSeedCreateRoute,
  ClientLandLandIdUpdateRoute: ClientLandLandIdUpdateRoute,
  ConsultantRecommendationRecIdUpdateRoute:
    ConsultantRecommendationRecIdUpdateRoute,
  ConsultantSeedSeedIdUpdateRoute: ConsultantSeedSeedIdUpdateRoute,
  ClientLandLandIdIndexRoute: ClientLandLandIdIndexRoute,
  ConsultantRecommendationRecIdIndexRoute:
    ConsultantRecommendationRecIdIndexRoute,
  ConsultantSeedSeedIdIndexRoute: ConsultantSeedSeedIdIndexRoute,
  ClientLandLandIdAutomationCreateRoute: ClientLandLandIdAutomationCreateRoute,
  ClientLandLandIdPestControlCreateRoute:
    ClientLandLandIdPestControlCreateRoute,
  ClientLandLandIdPlantCreateRoute: ClientLandLandIdPlantCreateRoute,
  ClientLandLandIdPumpCreateRoute: ClientLandLandIdPumpCreateRoute,
  ClientLandLandIdSensorCreateRoute: ClientLandLandIdSensorCreateRoute,
  ClientLandLandIdValveCreateRoute: ClientLandLandIdValveCreateRoute,
  ClientLandLandIdAutomationAutomationIdUpdateRoute:
    ClientLandLandIdAutomationAutomationIdUpdateRoute,
  ClientLandLandIdPestControlPestIdUpdateRoute:
    ClientLandLandIdPestControlPestIdUpdateRoute,
  ClientLandLandIdPlantPlantIdUpdateRoute:
    ClientLandLandIdPlantPlantIdUpdateRoute,
  ClientLandLandIdPumpPumpIdUpdateRoute: ClientLandLandIdPumpPumpIdUpdateRoute,
  ClientLandLandIdSensorSensorIdUpdateRoute:
    ClientLandLandIdSensorSensorIdUpdateRoute,
  ClientLandLandIdValveValveIdUpdateRoute:
    ClientLandLandIdValveValveIdUpdateRoute,
  ClientLandLandIdAutomationAutomationIdIndexRoute:
    ClientLandLandIdAutomationAutomationIdIndexRoute,
  ClientLandLandIdPestControlPestIdIndexRoute:
    ClientLandLandIdPestControlPestIdIndexRoute,
  ClientLandLandIdPlantPlantIdIndexRoute:
    ClientLandLandIdPlantPlantIdIndexRoute,
  ClientLandLandIdPumpPumpIdIndexRoute: ClientLandLandIdPumpPumpIdIndexRoute,
  ClientLandLandIdSensorSensorIdIndexRoute:
    ClientLandLandIdSensorSensorIdIndexRoute,
  ClientLandLandIdValveValveIdIndexRoute:
    ClientLandLandIdValveValveIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
